const daysOfTheWeek = ['Monday', 'Tuesday', 'Wednesday', 'Thursday','Friday','Saturday','Sunday'];

function getDay(){
 return daysOfTheWeek[Math.floor(Math.random() * daysOfTheWeek.length)];
}

const shoes = [
	{'type': 'boots', 'color': 'black', 'sex': 'man', day:getDay()},
	{'type': 'boots', 'color': 'black', 'sex': 'woman', day:getDay()},
	{'type': 'boots', 'color': 'brown', 'sex': 'man', day:getDay()},
	{'type': 'boots', 'color': 'brown', 'sex': 'woman', day:getDay()},
	{'type': 'boots', 'color': 'white', 'sex': 'man', day:getDay()},
	{'type': 'boots', 'color': 'white', 'sex': 'woman', day:getDay()},
	{'type': 'boots', 'color': 'beige', 'sex': 'man', day:getDay()},
	{'type': 'boots', 'color': 'beige', 'sex': 'woman', day:getDay()},
	{'type': 'boots', 'color': 'red', 'sex': 'man', day:getDay()},
	{'type': 'boots', 'color': 'red', 'sex': 'woman', day:getDay()},
	{'type': 'boots', 'color': 'blue', 'sex': 'man', day:getDay()},
	{'type': 'boots', 'color': 'blue', 'sex': 'woman', day:getDay()},
	{'type': 'shoes','color': 'black','sex': 'man', day:getDay()},
	{'type': 'shoes','color': 'black','sex': 'woman', day:getDay()},
	{'type': 'shoes','color': 'brown','sex': 'man', day:getDay()},
	{'type': 'shoes','color': 'brown','sex': 'woman', day:getDay()},
	{'type': 'shoes','color': 'white','sex': 'man', day:getDay()},
	{'type': 'shoes','color': 'white','sex': 'woman', day:getDay()},
	{'type': 'shoes','color': 'beige','sex': 'man', day:getDay()},
	{'type': 'shoes','color': 'beige','sex': 'woman', day:getDay()},
	{'type': 'shoes','color': 'red','sex': 'man', day:getDay()},
	{'type': 'shoes','color': 'red','sex': 'woman', day:getDay()},
	{'type': 'shoes','color': 'blue','sex': 'man', day:getDay()},
	{'type': 'shoes','color': 'blue','sex': 'woman', day:getDay()},
	{'type': 'sandals','color': 'black','sex': 'man', day:getDay()},
	{'type': 'sandals','color': 'black','sex': 'woman', day:getDay()},
	{'type': 'sandals','color': 'brown','sex': 'man', day:getDay()},
	{'type': 'sandals','color': 'brown','sex': 'woman', day:getDay()},
	{'type': 'sandals','color': 'white','sex': 'man', day:getDay()},
	{'type': 'sandals','color': 'white','sex': 'woman', day:getDay()},
	{'type': 'sandals','color': 'beige','sex': 'man', day:getDay()},
	{'type': 'sandals','color': 'beige','sex': 'woman', day:getDay()},
	{'type': 'sandals','color': 'red','sex': 'man', day:getDay()},
	{'type': 'sandals','color': 'red','sex': 'woman', day:getDay()},
	{'type': 'sandals','color': 'blue','sex': 'man', day:getDay()},
	{'type': 'sandals','color': 'blue','sex': 'woman', day:getDay()},
	{'type': 'gumshoes','color': 'black','sex': 'man', day:getDay()},
	{'type': 'gumshoes','color': 'black','sex': 'woman', day:getDay()},
	{'type': 'gumshoes','color': 'brown','sex': 'man', day:getDay()},
	{'type': 'gumshoes','color': 'brown','sex': 'woman', day:getDay()},
	{'type': 'gumshoes','color': 'white','sex': 'man', day:getDay()},
	{'type': 'gumshoes','color': 'white','sex': 'woman', day:getDay()},
	{'type': 'gumshoes','color': 'beige','sex': 'man', day:getDay()},
	{'type': 'gumshoes','color': 'beige','sex': 'woman', day:getDay()},
	{'type': 'gumshoes','color': 'red','sex': 'man', day:getDay()},
	{'type': 'gumshoes','color': 'red','sex': 'woman', day:getDay()},
	{'type': 'gumshoes','color': 'blue','sex': 'man', day:getDay()},
	{'type': 'gumshoes','color': 'blue','sex': 'woman', day:getDay()},
	{'type': 'sneakers','color': 'black','sex': 'man', day:getDay()},
	{'type': 'sneakers','color': 'black','sex': 'woman', day:getDay()},
	{'type': 'sneakers','color': 'brown','sex': 'man', day:getDay()},
	{'type': 'sneakers','color': 'brown','sex': 'woman', day:getDay()},
	{'type': 'sneakers','color': 'white','sex': 'man', day:getDay()},
	{'type': 'sneakers','color': 'white','sex': 'woman', day:getDay()},
	{'type': 'sneakers','color': 'beige','sex': 'man', day:getDay()},
	{'type': 'sneakers','color': 'beige','sex': 'woman', day:getDay()},
	{'type': 'sneakers','color': 'red','sex': 'man', day:getDay()},
	{'type': 'sneakers','color': 'red','sex': 'woman', day:getDay()},
	{'type': 'sneakers','color': 'blue','sex': 'man', day:getDay()},
	{'type': 'sneakers','color': 'blue','sex': 'woman', day:getDay()},
	{'type': 'slippers','color': 'black','sex': 'man', day:getDay()},
	{'type': 'slippers','color': 'black','sex': 'woman', day:getDay()},
	{'type': 'slippers','color': 'brown','sex': 'man', day:getDay()},
	{'type': 'slippers','color': 'brown','sex': 'woman', day:getDay()},
	{'type': 'slippers','color': 'white','sex': 'man', day:getDay()},
	{'type': 'slippers','color': 'white','sex': 'woman', day:getDay()},
	{'type': 'slippers','color': 'beige','sex': 'man', day:getDay()},
	{'type': 'slippers','color': 'beige','sex': 'woman', day:getDay()},
	{'type': 'slippers','color': 'red','sex': 'man', day:getDay()},
	{'type': 'slippers','color': 'red','sex': 'woman', day:getDay()},
	{'type': 'slippers','color': 'blue','sex': 'man', day:getDay()},
	{'type': 'slippers','color': 'blue','sex': 'woman', day:getDay()},
];

export {shoes};
